name: publish

on:
  release:
    types: [published]

env:
  node-version: 22

jobs:
  publish-universal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build -w @tiny-type-api/universal
      - run: cp ./README.md ./packages/universal/README.md
      - run: npm publish -w @tiny-type-api/universal --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build -w @tiny-type-api/client
      - run: cp ./README.md ./packages/client/README.md
      - run: npm publish -w @tiny-type-api/client --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
