name: publish

on:
  release:
    types: [published]

jobs:
  publish-universal:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 20.x
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build -w @tiny-type-api/universal
      - run: npm publish -w @tiny-type-api/universal --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-client:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 20.x
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build -w @tiny-type-api/client
      - run: npm publish -w @tiny-type-api/client --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
